<?xml version="1.0"?>
<package format="3">
  <name>sn2031674_manual_rc</name>
  <version>0.1.0</version>
  <description>Manual DJI RC to DShot controller for EtherCAT slave sn2031674.</description>
  <maintainer email="maintainer@example.com">ssybh2</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>custom_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
